import type { Registro } from "../types";

export const SEED_REGISTROS: Registro[] = [
 {
  "id": 1,
  "fecha": "2026-02-11",
  "tipo": "Donación realizada",
  "eje": "DEPORTE Y TRANSFORMACIÓN SOCIAL",
  "unidad": "SHERATON HOTEL Y HUENTALA HOTEL",
  "beneficiario": "FUNDACIÓN QUITA PENAS",
  "aporte": "15 SÁBANAS KING Y 10 TWIN",
  "motivo": "DAMNIFICADOS EN ASENTAMIENTO",
  "costo": 88527.53,
  "contacto": "RAUL BEGUIER",
  "constancia": "No",
  "observaciones": null,
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 2,
  "fecha": "2026-02-13",
  "tipo": "Donación realizada",
  "eje": "INFANCIA Y EDUCACIÓN",
  "unidad": "FUNDACIÓN",
  "beneficiario": "PROYECTO MOCHI",
  "aporte": "10 MOCHILAS",
  "motivo": "NIÑOS Y NIÑAS EN SITUACIÓN DE VULNERABILIDAD, PROMOVER LA INCLUSIÓN SOCIAL Y ACCESO A MEJORES CONDICIONES EDUCATIVAS",
  "costo": 246236.55,
  "contacto": "RETIRA FABIANA INSEGNA",
  "constancia": "No",
  "observaciones": "MOCHILAS PARA NIÑOS Y NIÑAS DE 2DO, 3ERO, 5TO Y 6TO GRADO. ",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 3,
  "fecha": "2026-03-13",
  "tipo": "Donación realizada",
  "eje": "DEPORTE Y TRANSFORMACIÓN SOCIAL",
  "unidad": "FUNDACIÓN",
  "beneficiario": "PESCA CON MOSCA PARA HOMBRES CON CÁNCER",
  "aporte": "MEDIATARDE",
  "motivo": null,
  "costo": 67760,
  "contacto": null,
  "constancia": "No",
  "observaciones": null,
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 4,
  "fecha": "2026-04-04",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "FUNDACIÓN",
  "beneficiario": "ASOCIACIÓN CIVIL CROATAS EN MENDOZA HRVATSKI DOM",
  "aporte": "AUSPICIO DE CONCURSO PISANICE, HUEVOS GIGANTES PINTADOS EN VIVO",
  "motivo": "AUSPICIO OBRA PICTÓRICA",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "SE AUSPICIA OBRA PICTÓRICA N11 \"TRANSFORMACIÓN Y AMOR\" DE TANIA DRIVAN REALIZADA EN PALMARES MALL, DEL 31/03 AL 04/4. OBTENCIÓN SEGUNDO PREMIO",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 5,
  "fecha": "2026-04-05",
  "tipo": "Donación realizada",
  "eje": "DEPORTE Y TRANSFORMACIÓN SOCIAL",
  "unidad": "FUNDACIÓN",
  "beneficiario": "PASTORAL DE CALLE",
  "aporte": "2 HUEVOS DE PASCUA DE, CADA UNO",
  "motivo": "PASCUAS",
  "costo": null,
  "contacto": "ANDREA CORTES",
  "constancia": "No",
  "observaciones": null,
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 6,
  "fecha": "2026-04-16",
  "tipo": "Donación realizada",
  "eje": "DEPORTE Y TRANSFORMACIÓN SOCIAL",
  "unidad": "SHERATON",
  "beneficiario": "FAMILIA DAMNIFICADA",
  "aporte": "3 FRAZADAS, 3 JUEGOS DE SÁBANAS TWIN, 3 ALMOHADAS, 3 PLATOS PLAYOS ",
  "motivo": "AYUDA FAMILIA DAMNIFICADA",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "DONACIÓN REALIZADA A TRAVÉS DE MAURICIO MIRANDA",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 7,
  "fecha": "2026-06-29",
  "tipo": "Donación realizada",
  "eje": "DEPORTE Y TRANSFORMACIÓN SOCIAL",
  "unidad": "FUNDACIÓN",
  "beneficiario": "COMUNIDAD DE VENEZOLANOS EN MENDOZA",
  "aporte": "DONACIÓN DE ELEMENTOS DE HIGIENE Y PRIMERA NECESIDAD",
  "motivo": "AYUDA A VICTIMAS DAMNIFICADAS POR TERREMOTOS EN VENEZUELA",
  "costo": null,
  "contacto": "ANGELICA CARVAJAL",
  "constancia": "No",
  "observaciones": "DESDE FUNDACIÓN NOS SUMAMOS A RECOLECTAR DONACIONES PARA ENVIAR A LOS DAMNIFICADOS AFECTADOR POR EL TERREMOTO EN VENEZUELA",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 8,
  "fecha": "2026-07-16",
  "tipo": "Donación realizada",
  "eje": "DEPORTE Y TRANSFORMACIÓN SOCIAL",
  "unidad": "SHERATON Y HUENTALA",
  "beneficiario": "CENTRO DE JUBILADOS MANUEL BELGRANO DE GLLEN",
  "aporte": "DONACIÓN DE 2 TVS EN DESUSO Y 1 VOUCHER DE DESAYUNO EN HUENTALA",
  "motivo": "APOYAR LAS ACCIONES QUE DESARROLLA EL CENTRO DE JUBILADOS, CON LA DONACIÓN PARA QUE PUEDAN REALIZAR UN SORTEO Y ASÍ PODER DARLE CONTINUIDAD A SUS ACTIVIDADES",
  "costo": null,
  "contacto": "AMELIA CRISTINA GAZAL Y CRISTINA VARGAS",
  "constancia": "No",
  "observaciones": null,
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 9,
  "fecha": "2026-07-16",
  "tipo": "Donación realizada",
  "eje": "INFANCIA Y EDUCACIÓN",
  "unidad": "SHERATON HOTEL Y HUENTALA HOTEL",
  "beneficiario": "FUNDACIÓN PESCAR EN CIUDAD",
  "aporte": "DESAYUNO, VIATICOS, ",
  "motivo": "PASANTIA DOS VECES AL MES",
  "costo": 152000,
  "contacto": null,
  "constancia": "No",
  "observaciones": "DESAYUNO + VIÁTICOS P/P (2800)=$76.000 POR CADA VISITA",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 10,
  "fecha": null,
  "tipo": "Donación realizada",
  "eje": "INFANCIA Y EDUCACIÓN",
  "unidad": "HUENTALA WINES",
  "beneficiario": "FUNDACIÓN PESCAR EN VALLE DE UCO",
  "aporte": "DESAYUNO, VIATICOS, ",
  "motivo": "PASANTIA TODOS LOS MIÉRCOLES",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "SALÓN + DESAYUNO (APROX. $1000 P/P)",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 11,
  "fecha": "2026-07-20",
  "tipo": "Donación realizada",
  "eje": "INFANCIA Y EDUCACIÓN",
  "unidad": "FUNDACIÓN",
  "beneficiario": "COLECTA DE JUGUETES",
  "aporte": "COLECTAR JUGUETES PARA DONAR EN EL MARCO DEL DIA DEL NIÑO / DIA DE LAS INFANCIAS",
  "motivo": "DIA DEL NIÑO / DIA DE LAS INFANCIAS",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "A DEFINIR ENTIDAD A BENEFICIAR. CAMPAÑA ACTIVA HASTA 13 AGOSTO",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 12,
  "fecha": "2026-07-30",
  "tipo": "Donación realizada",
  "eje": "INFANCIA Y EDUCACIÓN",
  "unidad": "FUNDACIÓN",
  "beneficiario": "DGP DIRECCIÓN GENERAL DE PROTECCIÓN",
  "aporte": "10 BULTOS CON ROPA DE NIÑOS DE 0 A 12AÑOS",
  "motivo": "COMPROMISO CON EL BIENESTAR, PROTECCIÓN Y DESARROLLO DE NIÑOS Y NIÑAS EN TRANSITO EN LOS HOGARES",
  "costo": null,
  "contacto": "BELEN GARCIA",
  "constancia": "No",
  "observaciones": "SE DONA ROPA DE NIÑOS RECOLECTADA EN LA CAMAPAÑA DE INVIERNO ACTIVA Y RECIBIDA A TRAVÉS DE LA ACCIÓN POR VENEZUELA ( QUE NO PUDO ENVIARSE A DICHO PAIS) ",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 13,
  "fecha": "2026-08-01",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON",
  "beneficiario": "TALLER LOS PIOJOS",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ARTE KIDS ",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "FUNDACIÓN HUENTALA Y TALLER LOS PIOJOS PRESENTAN UNA NUEVA EDICION, EN ESTA OPORTUNIDAD INSPIRADA EN EL ARTISTA EDUARDO HOFFMANN. SE COLOCAN A LA VENTA TOTEBAGS INTERVENIDAS POR LOS CHICOS DEL TALLE, Y LO RECAUDADO SERÁ DESTINADO A COMPRAR MATERIALES PARA LOS CHICOS.",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 14,
  "fecha": "2026-08-19",
  "tipo": "Donación realizada",
  "eje": "INFANCIA Y EDUCACIÓN",
  "unidad": "SHERATON",
  "beneficiario": "FUNDACIÓN ADN",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "EVENTO ADNIA LAB",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "EVENTO A DESARROLLARSE EN EL SALÓN FADER. LA FUNDACIÓN ADN CONTRATÓ COFFEES Y TÉCNICA PARA 100 PERSONAS. FERNANDO OLIVA ES SPEAKER",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 15,
  "fecha": "2026-08-21",
  "tipo": "Donación realizada",
  "eje": "DEPORTE Y TRANSFORMACIÓN SOCIAL",
  "unidad": "SHERATON Y HUALTA",
  "beneficiario": "6TO TORNEO DE GOLF SOLIDARIO",
  "aporte": "2 CAJAS DE ESPUMANTE SOMBRERO, 1 VOUCHER DE DESAYUNO EN HUALTA Y 1 VOUCHER DE DESAYUNO EN SHERATON",
  "motivo": "TORNEO SOLIDARIO DE GOLF",
  "costo": null,
  "contacto": "Dra. María Estela Caccavo de Estefan",
  "constancia": "No",
  "observaciones": "2 cajas de espumante Sombrero Extra Brut, 1 voucher de desayuno para dos personas en Hualta y 1 voucher de desayuno para dos personas en Huentala. Donados a la Fundación CETAI (Instituto Estefan)",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 16,
  "fecha": null,
  "tipo": "Donación realizada",
  "eje": "DEPORTE Y TRANSFORMACIÓN SOCIAL",
  "unidad": "FUNDACIÓN",
  "beneficiario": "KKL",
  "aporte": "DONACIÓN DE 5 ÁRBOLES PARA NUEVO PARQUE EN PROVINCIA DE MENDOZA",
  "motivo": null,
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "[Fecha original ambigua en Excel: 9/10/11 OCT]",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 17,
  "fecha": "2025-03-01",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "FERNANDO DE ROSAS",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA HUENTALA WINES",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 18,
  "fecha": "2025-03-06",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "HUENTALA HOTEL",
  "beneficiario": "FABIANA KANEFSCK",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA HUENTALA WINES",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 19,
  "fecha": "2025-03-14",
  "tipo": "Donación realizada",
  "eje": "DEPORTE Y TRANSFORMACIÓN SOCIAL",
  "unidad": "FUNDACIÓN",
  "beneficiario": "CENTRO INTEGRADOR DE DONACIONES PARA BAHÍA BLANCA",
  "aporte": "ESPACIO DE ALMACENAMIENTO",
  "motivo": "INUNDACIONES EN BAHÍA BLANCA",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "SE BUSCA CENTRALIZAR Y CONSOLIDAR DONACIONES PARA CANALIZARLAS HACIA INSTITUCIONES PÚBLICAS O PRIVADAS QUE ESTÉN ORGANIZANDO VIAJES DE AYUDA A LA CIUDAD. NUESTRO OBJETIVO ES TRANSFORMAR ESTE ESFUERZO EN UNA INICIATIVA ESTRUCTURADA Y ESCALABLE, FACILITANDO LA LOGÍSTICA PARA QUE MÁS ORGANIZACIONES Y CIUDADANOS PUEDAN COLABORAR DE MANERA EFECTIVA.",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 20,
  "fecha": "2025-03-18",
  "tipo": "Donación realizada",
  "eje": "INFANCIA Y EDUCACIÓN",
  "unidad": "FUNDACIÓN",
  "beneficiario": "ESCUELA N° 1-510 GUSTAVO MARTINEZ ZUVIRIA",
  "aporte": "4 SILLAS",
  "motivo": "CONTRIBUIR A LA MEJORA DEL APRENDIZAJE DE LOS ALUMNOS Y EL CONFORT DE LOS DOCENTES DE LA ESCUELA. ",
  "costo": null,
  "contacto": "MARISA PINNA DIRECTORA. ",
  "constancia": "No",
  "observaciones": null,
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 21,
  "fecha": "2025-04-22",
  "tipo": "Donación realizada",
  "eje": "SEGURIDAD ALIMENTARIA Y NUTRICIÓN",
  "unidad": "FUNDACIÓN",
  "beneficiario": "FUNDACIÓN VÍNCULOS",
  "aporte": "20KG DE CHOCOLATE (CASITA DE CHOCOLATE)",
  "motivo": "DONACIÓN EN PASCUAS",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "DONACIÓN DE PARTE DE LOS HUEVOS DE PASCUAS EN LA TRADICIONAL EXPOSICIÓN",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 22,
  "fecha": "2025-04-22",
  "tipo": "Donación realizada",
  "eje": "SEGURIDAD ALIMENTARIA Y NUTRICIÓN",
  "unidad": "FUNDACIÓN",
  "beneficiario": "ESCUELA JUAN GONZALEZ ORO",
  "aporte": "HUEVO DE PASCUA",
  "motivo": "DONACIÓN EN PASCUAS",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ESCUELA DE TUPUNGATO",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 23,
  "fecha": "2025-05-08",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "HUENTALA HOTEL",
  "beneficiario": "SILVINA MUZZINO",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA HUENTALA WINES",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 24,
  "fecha": "2025-05-16",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL Y HUALTA HOTEL",
  "beneficiario": "BARBI NEGRONI",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA HUENTALA WINES",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 25,
  "fecha": "2025-06-05",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "HUENTALA HOTEL",
  "beneficiario": "YANI TORANZO",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA HUENTALA WINES",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 26,
  "fecha": "2025-06-12",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "HUALTA HOTEL",
  "beneficiario": "FERNANDA PIAMONTI",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA HUENTALA WINES",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 27,
  "fecha": "2025-06-28",
  "tipo": "Donación realizada",
  "eje": "SEGURIDAD ALIMENTARIA Y NUTRICIÓN",
  "unidad": "FUNDACIÓN",
  "beneficiario": "REFUGIO HUENTALA",
  "aporte": "ESPACIO CON 40 PLAZAS, CALEFACCIÓN, DESAYUNO",
  "motivo": "MESES INVERNALES",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "SALA SAN JUAN: FUNCIONAMIENTO DE 19HS A 11HS. EN COLABORACIÓN CON LA PASTORAL DEL ARZOBISPADO DE MENDOZA Y LA MUNICIPALIDAD DE LA CIUDAD DE MENDDOZA | REVISAR EJE: originalmente cargado como 'SEGURIDAD ALIMENTARIA Y NUTRICIÓN, EMPLEABILIDAD Y DESARROLLO ECONÓMICO'. Se dejó Seguridad Alimentaria y Nutrición como principal; confirmar o mover a Empleabilidad.",
  "difusion": "https://www.fmutn.com.ar/extienden-plazo-de-albergues-para-personas-en-situacion-de-calle-en-mendoza/",
  "horas": null,
  "inversion": null
 },
 {
  "id": 28,
  "fecha": "2025-07-18",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "HUENTALA HOTEL",
  "beneficiario": "MARIANA PELICHONE",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA HUENTALA WINES",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 29,
  "fecha": "2025-09-06",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "ARTEKIDS CON PIOJOS TALLER DE ARTE",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ARTE KIDS",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "FUNDACIÓN HUENTALA Y PIOJOS TALLER DE ARTE, PRESENTAN UNA MUESTRA CON OBRAS DE NIÑOS INSPIRADAS EN EL ARTISTA SERGIO ROGGERONE. LE ENTRADA ES UN ALIMENTO NO PERECEDERO O CAJA DE LECHE PARA RECAUDACIÓN SOLIDARIA.\n",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 30,
  "fecha": "2025-10-30",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "HUENTALA HOTEL",
  "beneficiario": "SERGIO GRINBERG",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA HUENTALA WINES",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 31,
  "fecha": "2025-11-01",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "HUENTALA WINES",
  "beneficiario": "KEHILA MENDOZA",
  "aporte": "2 CAJAS DE VINO DREIDEL",
  "motivo": null,
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "DESDE KEHILA MENDOZA REALIZAN LA COMPRA DE 6 CAJAS DE VINO DREIDEL, ETIQUETA ROJA, Y SE DONAN 2 CAJAS EXTRA AL PEDIDO. ",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 32,
  "fecha": "2025-11-04",
  "tipo": "Donación realizada",
  "eje": "INFANCIA Y EDUCACIÓN",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "FUNDACIÓN PESCAR",
  "aporte": "SALÓN + COFFEE",
  "motivo": "EVENTO CIERRE AÑO DE PASANTIAS",
  "costo": 100000,
  "contacto": "FLOR FUNDACIÓN PESCAR +54 9 11 5478-3770",
  "constancia": "No",
  "observaciones": "MIRADOR",
  "difusion": "https://www.instagram.com/p/DQrgOiIkcix/?igsh=NWVhdGIyMWRtOW93",
  "horas": null,
  "inversion": null
 },
 {
  "id": 33,
  "fecha": "2025-11-13",
  "tipo": "Donación realizada",
  "eje": "DEPORTE Y TRANSFORMACIÓN SOCIAL",
  "unidad": "HUENTALA HOTEL",
  "beneficiario": "FUNDAVITA Y ASOCIACIÓN MUJERES PODEROSAS MENDOZA",
  "aporte": "SALÓN ",
  "motivo": "TALLER INTEGRAL PARA PACIENTES ONCOLÓGICAS DE CÁNCER MAMA",
  "costo": null,
  "contacto": "VIOLETA FUNDAVITA +54 9 2615 17-0400",
  "constancia": "No",
  "observaciones": "SALÓN CUYÚM",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 34,
  "fecha": "2025-11-16",
  "tipo": "Donación realizada",
  "eje": "DEPORTE Y TRANSFORMACIÓN SOCIAL",
  "unidad": "HUALTA HOTEL",
  "beneficiario": "COLEGIO ICEI",
  "aporte": "1 DESAYUNO P/ 2 PERSONAS",
  "motivo": "MARATÓN SOLIDARIA COLEGIO ICEI",
  "costo": null,
  "contacto": "SEÑO PAOLA  +54 9 2616 84-5643",
  "constancia": "No",
  "observaciones": "VALIDEZ HASTA 31/12/2025",
  "difusion": "https://www.instagram.com/s/aGlnaGxpZ2h0OjE4MzQ3MTAxMzA2MjA3Nzc3?story_media_id=3761637166322664667&igsh=MWpqMDU4MXllN2FxbQ==",
  "horas": null,
  "inversion": null
 },
 {
  "id": 35,
  "fecha": "2025-11-16",
  "tipo": "Donación realizada",
  "eje": "DEPORTE Y TRANSFORMACIÓN SOCIAL",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "COLEGIO ICEI",
  "aporte": "1 DESAYUNO P/ 2 PERSONAS",
  "motivo": "MARATÓN SOLIDARIA COLEGIO ICEI",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "VALIDEZ HASTA 31/12/2026",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 36,
  "fecha": "2025-11-16",
  "tipo": "Donación realizada",
  "eje": "DEPORTE Y TRANSFORMACIÓN SOCIAL",
  "unidad": "WINE SHOP",
  "beneficiario": "COLEGIO ICEI",
  "aporte": "1 BOTELLA MAGNUM \"SOMBRERO\"",
  "motivo": "MARATÓN SOLIDARIA COLEGIO ICEI",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": null,
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 37,
  "fecha": "2025-12-02",
  "tipo": "Donación realizada",
  "eje": "INFANCIA Y EDUCACIÓN",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "CCT ESCULTOR MATEO ALONSO - USPALLATA",
  "aporte": "VISITA / SITE",
  "motivo": "SITE PARA ESTUDIANTES DE CURSO DE CAMAREROS / MOZOS",
  "costo": null,
  "contacto": "MARIANA ARECHE 0261 - 155 05 41 14",
  "constancia": "No",
  "observaciones": "MOSTRAR ESPACIOS GASTRONÓMICOS PARA QUE LOS ESTUDIANTES PUEDAN VIVENCIAR LA EXPERIENCIA DESDE NUESTRO LADO LABORAL",
  "difusion": null,
  "horas": 2,
  "inversion": null
 },
 {
  "id": 38,
  "fecha": "2025-12-05",
  "tipo": "Donación realizada",
  "eje": "DEPORTE Y TRANSFORMACIÓN SOCIAL",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "CONGRESO DE LA FELICIDAD",
  "aporte": "SPONSOR",
  "motivo": "CONGRESO DE LA FELICIDAD",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": null,
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 39,
  "fecha": "2025-12-08",
  "tipo": "Donación realizada",
  "eje": "DEPORTE Y TRANSFORMACIÓN SOCIAL",
  "unidad": "FUNDACIÓN",
  "beneficiario": "CLUB MACABI",
  "aporte": "4 BOTELLAS DE VINO DREIDEL Y 2 BOTELLAS DE VINO SOMBRERO MALBEC",
  "motivo": "MACABI OPEN DAY",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": null,
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 40,
  "fecha": "2025-12-14",
  "tipo": "Donación realizada",
  "eje": "INFANCIA Y EDUCACIÓN",
  "unidad": "HUALTA HOTEL",
  "beneficiario": "MERENDERO LOS PAJARITOS",
  "aporte": "COMPRA DE JUGUETES MÁS JUGUETES TRAIDOS POR LOS ASISTENTES",
  "motivo": "EDICIÓN MUJERES CANTORAS ",
  "costo": 508242.55,
  "contacto": null,
  "constancia": "No",
  "observaciones": "\"SONRISAS QUE SUENAN\" EN JACARANDÁ GARDEN BAR, 19HS. ARTISTAS INVITADOS NÉCTAR 02 Y EMILIA ORLANDO. ENTRADA ARS 8000 + UN JUGUETE",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 41,
  "fecha": "2024-04-05",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON MENDOZA",
  "beneficiario": "PATO CADENAZZI",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA HUENTALA WINES. MUSICALIZA ALE CASTRO",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 42,
  "fecha": "2024-05-09",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "HUENTALA HOTEL",
  "beneficiario": "CASTELLANO MARCOS Y JUAN FERNANDO FENSEL",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA HUENTALA WINES. MUESTRA CONJUNTA CON EL CONSULADO DE ITALIA Y LA UNC. BODEGA HUENTALA WINES",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 43,
  "fecha": "2024-07-19",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "HUENTALA HOTEL",
  "beneficiario": "5TO ELEMENTO",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA HUENTALA WINES. AIRE, AGUA, TIERRA FUEGO Y EL ARTISTA. EXPOSICIÓN COLECTIVA DE FOTOGRAFÍA INTERVENCIÓN CON BAILARINES TRAIDOS POR ELIANA",
  "difusion": "MUESTRA DECLARADA DE INTERÉS PROVINCIAL POR LA HORABLE CÁMARA DE SENADORES DE LA PROVINCIA",
  "horas": null,
  "inversion": null
 },
 {
  "id": 44,
  "fecha": "2024-07-17",
  "tipo": "Donación realizada",
  "eje": "SEGURIDAD ALIMENTARIA Y NUTRICIÓN",
  "unidad": "FUNDACIÓN",
  "beneficiario": "REFUGIO HUENTALA",
  "aporte": "ESPACIO CON 40 PLAZAS, CALEFACCIÓN, DESAYUNO",
  "motivo": "MESES INVERNALES",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "SALA SAN JUAN: FUNCIONAMIENTO DE 19HS A 11HS. EN COLABORACIÓN CON LA PASTORAL DEL ARZOBISPADO DE MENDOZA Y LA MUNICIPALIDAD DE LA CIUDAD DE MENDDOZA | REVISAR EJE: originalmente cargado como 'SEGURIDAD ALIMENTARIA Y NUTRICIÓN, EMPLEABILIDAD Y DESARROLLO ECONÓMICO'. Se dejó Seguridad Alimentaria y Nutrición como principal; confirmar o mover a Empleabilidad.",
  "difusion": "https://www.elnueve.com/mendoza/quedo-habilitado-el-nuevo-refugio-de-mendoza-para-persona-en-situacion-de-calle_20240719/#google_vignette",
  "horas": null,
  "inversion": null
 },
 {
  "id": 45,
  "fecha": "2024-09-07",
  "tipo": "Donación realizada",
  "eje": "DEPORTE Y TRANSFORMACIÓN SOCIAL",
  "unidad": "FUNDACIÓN",
  "beneficiario": "EQUIPO DE FUTBOL LOBOS DE MAIPÚ",
  "aporte": "60 CAMISETAS DE NIÑOS",
  "motivo": "DONACIÓN",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACCIÓN EN CONJUNTO DE CHIMPAY S.A. Y CELA S.A.",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 46,
  "fecha": "2024-11-08",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON MENDOZA",
  "beneficiario": "TANIA DRIBAN MOLINELLI Y DIEGO MARAGNA",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA HUENTALA WINES. RENACIDOS",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 47,
  "fecha": "2024-11-15",
  "tipo": "Donación realizada",
  "eje": "DEPORTE Y TRANSFORMACIÓN SOCIAL",
  "unidad": "SHERATON MENDOZA",
  "beneficiario": "CASA RONALD MCDONALD",
  "aporte": "200 BLANCOS VARIOS",
  "motivo": "DONACIÓN",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "DONACIÓN",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 48,
  "fecha": "2025-11-15",
  "tipo": "Donación realizada",
  "eje": "DEPORTE Y TRANSFORMACIÓN SOCIAL",
  "unidad": "SHERATON MENDOZA",
  "beneficiario": "HOSPITAL NOTTI",
  "aporte": "160 BLANCOS VARIOS",
  "motivo": "DONACIÓN",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "DONACIÓN",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 49,
  "fecha": "2024-12-24",
  "tipo": "Donación realizada",
  "eje": "INFANCIA Y EDUCACIÓN",
  "unidad": "FUNDACIÓN",
  "beneficiario": "CASA RONALD MCDONALD",
  "aporte": "DONACIÓN DE JUGUETES Y MERIENDA",
  "motivo": "DONACIÓN",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "NAVIDAD",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 50,
  "fecha": "2023-03-01",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "HUENTALA HOTEL",
  "beneficiario": "CARLOS KRAVETS",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA HUENTALA WINES",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 51,
  "fecha": "2023-04-13",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "SANDRA PERSIA",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA ZUCCARDI Y ALE CASTRO",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 52,
  "fecha": "2023-06-01",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "SANDRA PERSIA",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA FOSTER LORCA Y ALE CASTRO",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 53,
  "fecha": "2023-10-06",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "HUENTALA HOTEL",
  "beneficiario": "ALEJANDRA VALOT",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA HUENTALA WINES",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 54,
  "fecha": "2022-01-20",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "DIEGO MARAGNA",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA HUENTALA WINES Y ALE CASTRO",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 55,
  "fecha": "2022-02-03",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "DIEGO MARAGNA",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEHA HUENTALA WINES, ALE CASTRO Y GATO FICCARDI",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 56,
  "fecha": "2022-03-03",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "SANDRA PERSIA",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA LUIGI BOSCA, ALE CASTRO Y FRANCOCK",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 57,
  "fecha": "2022-03-17",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "SANDRA PERSIA",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA LUIGI BOSCA Y ALE CASTRO",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 58,
  "fecha": "2022-04-07",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "JUAN PABLO INZIRILLO",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA NORTON Y ALE CASTRO",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 59,
  "fecha": "2022-04-21",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "JUAN PABLO INZIRILLO",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA NORTON Y ALE CASTRO",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 60,
  "fecha": "2022-05-12",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "CARLOS ESCORIZA",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA RAPICHE, ALE CASTRO Y UTER",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 61,
  "fecha": "2022-05-13",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "HUENTALA HOTEL",
  "beneficiario": "NANCY PAMPINATO",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑAN DIVERSAS BODEGAS Y SAXOFONISTA CONTRATADO POR LA ARTISTA",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 62,
  "fecha": "2022-05-26",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "CARLOS ESCORIZA",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA TRAPICHE, ALE CASTRO Y FRANCOCK",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 63,
  "fecha": "2022-08-13",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "HUENTALA HOTEL",
  "beneficiario": "ANA PENA",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑAN DIVERSAS BODEGAS",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 64,
  "fecha": "2022-08-25",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "CECILIA CARRERAS",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA CASARENA Y ALE CASTRO",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 65,
  "fecha": "2022-09-22",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "CECILIA CARRERAS",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA CASARENA, ALE CASTRO Y GATO FICCARDI",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 66,
  "fecha": "2022-11-10",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "PAULA DREIDEMIE",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA VIÑA LAS PERDICES, ALE CASTRO Y FRANCOCK",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 67,
  "fecha": "2022-12-09",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "EMANUEL CELIZ",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA VIÑA LAS PERDICES Y ALE CASTRO",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 68,
  "fecha": "2021-12-09",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "HUGO SANCHEZ BAUZÓN",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA HUENTALA WINES Y ALE CASTRO",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 69,
  "fecha": "2021-12-16",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "HUGO SANCHEZ BAUZÓN",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA HUENTALA WINES Y ALE CASTRO",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 70,
  "fecha": "2020-06-01",
  "tipo": "Donación realizada",
  "eje": "SEGURIDAD ALIMENTARIA Y NUTRICIÓN",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "BANCO DE ALIMENTOS",
  "aporte": "500 KG HARINA, 600 L. LECHE Y 80KG DE DULCE DE LECHE",
  "motivo": null,
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "PANDEMIA",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 71,
  "fecha": "2020-07-01",
  "tipo": "Donación realizada",
  "eje": "SEGURIDAD ALIMENTARIA Y NUTRICIÓN",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "BANCO DE ALIMENTOS",
  "aporte": "684 L DE LECHE, 80KG DE ARROZ, 11KG DE SALSA DEMI GLACE, 16 L. DE LECHE DE SOJA NATURAL Y 385KG DE PASTA SECA",
  "motivo": null,
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "PANDEMIA",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 72,
  "fecha": "2019-03-01",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "BLANCA RUIZ FONTANAROSA",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA HUENTALA WINES",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 73,
  "fecha": "2019-08-01",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "PAO INCHAUSPE",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA HUENTALA WINES",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 74,
  "fecha": "2019-10-01",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "MYRTA EMILIA ABRAHAM",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA HUENTALA WINES",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 75,
  "fecha": "2019-12-01",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "FERNANDO ROSAS",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA HUENTALA WINES",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 76,
  "fecha": "2018-03-21",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "MARTIN VILLALONGA",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA TRIVENTO",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 77,
  "fecha": "2018-07-21",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "BELÉN SPPIR",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": null,
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 78,
  "fecha": "2018-09-21",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "MARTA ZIRULNIK DE KOTLICK",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA HUENTALA WINES",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 79,
  "fecha": "2018-12-21",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "ATILIO SPINELLO",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA DIAMANDES",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 80,
  "fecha": "2017-03-01",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "DANIEL CIANCIO Y YAMINA MUÑOS DECARRE",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA HUENTALA WINES / SHOW DE ALEXANDER MATOS",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 81,
  "fecha": "2017-04-01",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "ANALIA MAMMOLI",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA BENEGAS",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 82,
  "fecha": "2017-05-01",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "ORLANDO LEYTES",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA CASARENA",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 83,
  "fecha": "2017-06-01",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "EDUARDO DOLONGIEWICH",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "SIN REGISTRO",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 84,
  "fecha": "2017-08-01",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "MARIA MARTA CALIRI",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA DOÑA PAULA",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 85,
  "fecha": "2017-09-01",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "MAR GILLI",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA ESCORIHUELA GASCÓN",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 86,
  "fecha": "2017-10-01",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "LUIS SORIA",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "SIN REGISTRO",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 87,
  "fecha": "2017-11-01",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "NANCY SPAMPINATO",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA EL ENEMIGO",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 88,
  "fecha": "2016-03-01",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "DANIEL GENOVESI",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA FAMILIA ZUCCARDI",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 89,
  "fecha": "2016-04-01",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "FLORENCIA AISE",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA RUTINI WINES",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 90,
  "fecha": "2016-05-01",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "FILIPPO",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA LA AZUL",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 91,
  "fecha": "2016-06-01",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "ANDREA ARIZU",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA VIÑA ALICIA",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 92,
  "fecha": "2016-07-01",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "MARCELO VON DER HEYDE",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA LAS PERDICES",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 93,
  "fecha": "2016-08-01",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "GONZALO ANTON",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA FAMILIA ZUCCARDI",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 94,
  "fecha": "2016-09-01",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "LEIRA ARBOT",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA ANGULO INNOCENTI",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 95,
  "fecha": "2016-10-01",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "JORGE SARASOLA",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA NORTON",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 96,
  "fecha": "2016-11-01",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "VFERÓNICA FURÓ",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "SIN REGISTRO",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 97,
  "fecha": "2015-08-01",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "TACHUELA",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA VISTALBA",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 98,
  "fecha": "2015-11-01",
  "tipo": "Donación realizada",
  "eje": "ARTE Y CULTURA",
  "unidad": "SHERATON HOTEL",
  "beneficiario": "GILDA MIRALLES",
  "aporte": "ESPACIO DE EXPOSICIÓN",
  "motivo": "ART & WINE",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "ACOMPAÑA BODEGA BUDEGUER",
  "difusion": null,
  "horas": null,
  "inversion": null
 },
 {
  "id": 99,
  "fecha": "2014-08-01",
  "tipo": "Donación realizada",
  "eje": "INFANCIA Y EDUCACIÓN",
  "unidad": "FUNDACIÓN",
  "beneficiario": "ESC. JUAN GONZALEZ ORO GUALTALLARY",
  "aporte": "MERIENDA Y JUGUETES",
  "motivo": "DÍA DEL NIÑO",
  "costo": null,
  "contacto": null,
  "constancia": "No",
  "observaciones": "SE REALIZA ACCIÓN DE DIFUSIÓN DE DONACIÓN A TRAVÉS DE LA COMPRA DE CAJAS DE VINO EN WINE SHOP, PARA QUE CLIENTES PUEDAN SUMARSE A LA MISMA. DEL 7 AL 10 AGOSTO",
  "difusion": null,
  "horas": null,
  "inversion": null
 }
];
